### ISSUE TITLE
KeyError: 0.0

### ISSUE THREAD

**Issue by avinashkarkada** [kolmank/interfaceff2gro#4] opened 2022-11-21 06:44 UTC
Traceback (most recent call last):
  File "/home/aka/Desktop/alumina/interfaceff2gro-master/./interfaceff2gro.py", line 322, in <module>
    gro_file.write(gro_format%(1,'SURF',mass2element[m[1]],m[0]+1,m[2][0]/10,m[2][1]/10,m[2][2]/10))

Got the following error when running "./interfaceff2gro.py slab.car" for a slab of Al2O3

**Comment by kolmank** [comment] 2022-12-14 08:13
Hello avinashkarkada,
Sorry for the late answer. Could you provide me with the input files for your alumina slab (car and mdf files)? I assume that the problem is slightly different mass of Al atom which causes conversion to fail. It should be quite easy to fix.

Best regards,
Krzysztof

**Comment by kolmank** [comment] 2023-02-07 07:36
Since there is no answert from you, I close the issue.

**Closed as completed by kolmank** 2023-02-07 07:36 UTC
